test: hash: Use signed test vectors
Avoid GCC overflow warnings by using signed numbers instead of hex
numbers larger than 127.

    i586-pc-msdosdjgpp-gcc  -I../src/../include -O3 -DNDEBUG -Wall -Werror -Wextra -std=c89 -pedantic -MD -MT tests/CMakeFiles/test_hash.dir/hash.c.obj -MF tests/CMakeFiles/test_hash.dir/hash.c.obj.d -o tests/CMakeFiles/test_hash.dir/hash.c.obj -c ../tests/hash.c
    ../tests/hash.c: In function 'hash_test_deadbeef':
    ../tests/hash.c:26:20: error: overflow in conversion from 'int' to 'char' changes value from '222' to '-34' [-Werror=overflow]
       26 |     char test[] = {0xde, 0xad, 0xbe, 0xef, 0x00, 0xa5, 0x5a};
          |                    ^~~~
    ../tests/hash.c:26:26: error: overflow in conversion from 'int' to 'char' changes value from '173' to '-83' [-Werror=overflow]
       26 |     char test[] = {0xde, 0xad, 0xbe, 0xef, 0x00, 0xa5, 0x5a};
          |                          ^~~~
    ../tests/hash.c:26:32: error: overflow in conversion from 'int' to 'char' changes value from '190' to '-66' [-Werror=overflow]
       26 |     char test[] = {0xde, 0xad, 0xbe, 0xef, 0x00, 0xa5, 0x5a};
          |                                ^~~~
    ../tests/hash.c:26:38: error: overflow in conversion from 'int' to 'char' changes value from '239' to '-17' [-Werror=overflow]
       26 |     char test[] = {0xde, 0xad, 0xbe, 0xef, 0x00, 0xa5, 0x5a};
          |                                      ^~~~
    ../tests/hash.c:26:50: error: overflow in conversion from 'int' to 'char' changes value from '165' to '-91' [-Werror=overflow]
       26 |     char test[] = {0xde, 0xad, 0xbe, 0xef, 0x00, 0xa5, 0x5a};
          |                                                  ^~~~